Fixed a crasher that caused Leo to exit.  All tests pass.
openUrlOnClick
    if not w.hasSelection():
AttributeError: 'QTextBrowser' object has no attribute 'hasSelection'

- g.openUrlOnClick now catches all exceptions, so this kind of thing can never happen again.
- g.openUrlHelper now issues g.internal_error if w is not a text wrapper.
- vr.ensure_text_widget now creates a temp text wrapper to handle clicks.

Leo build: 20170216093355